### PR TITLE
feat: fixing usage of peak options close #31

### LINKED ISSUE #31: peak options is ignored with shape options is not defined

### PR DESCRIPTION
**Pull request by jobo322**

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -120,11 +119,11 @@ export class SpectrumGenerator {
         : peakWidth,
       widthLeft,
       widthRight,
-      shape: shapeOptions,
+      shape: shapeOptions = {},
     } = options;
 
     if (peakOptions) {
-      Object.assign(shapeOptions || {}, peakOptions || {});
+      shapeOptions = Object.assign({}, shapeOptions, peakOptions);
```
Comment (lpatiny) [inline src/index.js:126]: Please use the new syntax
```suggestion
      shapeOptions = {...shapeOptions, ...peakOptions};
```
`{...shapeOptions, ...peakOptions}`

**Review by lpatiny — CHANGES_REQUESTED** [review]

**Comment by targos** [comment]
Please add a test case.

**Comment by jobo322** [comment]
Actually, the correct name for these "peak options" is "shape", which continues with the global idea of shape options.
